package ISSUE_FAULTLOG_RuleSet
expander issue.dsl

import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelper;
import com.idsscheer.webapps.arcm.bl.component.issuemanagement.re.IssueHelperBB;

# OBJECT        client_objid         LONG       Client ID                                                                                                                                                   
# OBJECT        client_sign          CLIENTSIGN Client                                                                                                                                                      
# OBJECT        create_date          DATE       Creation date                                                                                                                                               
# OBJECT        creator_user_id      LONG       User ID (creator)                                                                                                                                           
# OBJECT        delete_date          DATE       Deletion date                                                                                                                                               
# OBJECT        guid                 STRING     GUID                                                                                                                                                        
# OBJECT        obj_id               LONG       ID                                                                                                                                                          
# OBJECT        obj_type             OBJECTTYPE Object type                                                                                                                                                 
# OBJECT        root_guid            STRING     Root GUID                                                                                                                                                   
# OBJECT        versions             LONG       Number of versions                                                                                                                                          
# VERSION       aris_change_date     DATE       ARIS change date                                                                                                                                            
# VERSION       change_date          DATE       Change date                                                                                                                                                 
# VERSION       change_type          ENUM       Change type                changetype (created=0,unchanged=1,changed=2,deleted=3,xmlcreated=4,xmlchanged=5,xmldeleted=6)                                    
# VERSION       change_user_id       LONG       User ID (editor)                                                                                                                                            
# VERSION       deactivated          BOOLEAN    Deactivated                                                                                                                                                 
# VERSION       id                   LONG       ID                                                                                                                                                          
# VERSION       substitute_user_id   LONG       User ID (substitute)                                                                                                                                        
# VERSION       version_active       BOOLEAN    Current version                                                                                                                                             
# VERSION       version_number       LONG       Version number                                                                                                                                              
# TRANSACTIONAL execution_date       DATE       Processed on                                                                                                                                                
# TRANSACTIONAL owner                LIST       Performed by               to 1 USER (LT=3105)                                                                                                              
# TRANSACTIONAL owner_group          LIST       Owner group                to 0 USERGROUPs (LT=4019)                                                                                                        
# TRANSACTIONAL owner_status         ENUM       Owner status               issue_owner_status (all=-1,open=0,to_be_reviewed=-2,new=1,in_progress=2,finished=3,on_hold=4,not_possible=5,open_for_execution=6)
# TRANSACTIONAL owner_substitute     LIST       Performed by (substitute)  to 1 USER (LT=3106)                                                                                                              
# TRANSACTIONAL review_date          DATE       Review date                                                                                                                                                 
# TRANSACTIONAL reviewer             LIST       Reviewer                   to 1 USER (LT=4022)                                                                                                              
# TRANSACTIONAL reviewer_group       LIST       Reviewer group             to 0 USERGROUPs (LT=4021)                                                                                                        
# TRANSACTIONAL reviewer_status      ENUM       Reviewer status            issue_reviewer_status (all=-1,to_be_approved=1,approved=2,not_approved=3)                                                        
# TRANSACTIONAL reviewer_substitute  LIST       Reviewer (substitute)      to * USERs (LT=4023)                                                                                                             
# MONITORABLE   controlenddate       DATE       End of control period                                                                                                                                       
# MONITORABLE   controlstartdate     DATE       Start of control period                                                                                                                                     
# MONITORABLE   plannedenddate       DATE       Remediation planned before                                                                                                                                  
# MONITORABLE   plannedstartdate     DATE       Start date                                                                                                                                                  
# ISSUE         category             ENUM       Issue category             issue_category (all=-1,please_select=0,finance=1,compliance=2,operations=3)                                                      
# ISSUE         created_by_testcase  BOOLEAN    Generated by test case                                                                                                                                      
# ISSUE         creator              LIST       Issue creator              to 1 USER (LT=3103)                                                                                                              
# ISSUE         creator_status       ENUM       Creator status             issue_creator_status (all=-1,open=0,new=1,in_creation=2,released=3)                                                              
# ISSUE         description          TEXT       Description                                                                                                                                                 
# ISSUE         documents            LIST       Documents                  to * DOCUMENTs (LT=3104)                                                                                                         
# ISSUE         immediateMeasure     TEXT       Immediate measure                                                                                                                                           
# ISSUE         issueRelevantObjects LIST       Issue-relevant objects     to * OBJECTs (LT=3102)                                                                                                           
# ISSUE         name                 STRING     Name                                                                                                                                                        
# ISSUE         owner_remark         TEXT       Remark (issue owner)                                                                                                                                        
# ISSUE         owners               LIST       Issue owner                to * USERs (LT=3100)                                                                                                             
# ISSUE         priority             ENUM       Priority                   issuePriority (all=-1,low=1,medium=2,high=3)                                                                                     
# ISSUE         relatedTestcaseID    LONG       ID (related test case)                                                                                                                                      
# ISSUE         remark               TEXT       Remark                                                                                                                                                      
# ISSUE         remediationMeasure   TEXT       Remediation measure                                                                                                                                         
# ISSUE         reviewer_remark      TEXT       Remark (issue reviewer)                                                                                                                                     
# ISSUE         reviewers            LIST       Issue reviewer             to * USERs (LT=3101)                                                                                                             
# ISSUE         stateTime            ENUM       Due status                 issueStateTime (all=-1,on_time=1,overdue=2)                                                                                      

# DO NOT CHANGE THE LINES ABOVE - all of them will be updated automatically by tool com.idsscheer.webapps.arcm.bl.re.RETemplater

########################
### BB CUSTOMIZATION ###
# rule engine needs to be executed when the attribute value of "bb_issueType" is changed.
rule "bb_issueType set to 'faultlog' --> set workflow actors mandatory for creator [I,V]"

	salience 2000
	no-loop true

	when
	    ( is in workflow state "PREPARED" OR
		  is in workflow state "openForCreation" )
	    # during creation the issue manager has the same rights as the creator
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "faultlog"

	then
		
		set "bb_implApproverL1_group" 	editable
		set "bb_mgmtApprover_orgunit" 	editable
		set "bb_implApprover_orgunit" 	editable
		
		set "remark"                  	editable
		set "priority"                	editable
		set "bb_issueGrade"           	editable
		set "bb_faultLogCategory"     	editable
		set "immediateMeasure"        	editable
		set "bb_anotherImportantInfo" 	editable
		set "bb_confidentialityLevel" 	editable
		
		set "bb_implApproverL1_group" 	mandatory
		set "bb_confidentialityLevel" 	mandatory
		set "bb_issueGrade"           	mandatory
		
		execute fault log rules	
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'faultlog' --> can creator group delegate issues [I,V]"

	salience 2000
	no-loop true

	when
	    ( is in workflow state "PREPARED" OR
		  is in workflow state "openForCreation" )
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "faultlog"
		can creator group delegate issues
		
	then
		
		set "bb_mgmtApproverL1_group" 		editable
		set "bb_mgmtApproverL2_group" 		editable
		
		set "bb_mgmtApproverL1_group" 		mandatory
		set "bb_mgmtApproverL2_group" 		mandatory
		
end

###############################################
### All workflow states - after state rules ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'faultlog' --> attributes for creator [I,V]"

	salience 2000
	no-loop true

	when
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "faultlog"

	then
		
		set "bb_mgmtApproverL1_group" 	visible
		set "bb_mgmtApproverL1_status" 	visible
		set "bb_mgmtApproverL1_remark" 	visible
		set "bb_mgmtApproverL1" 		visible
		set "bb_mgmtApproverL1_date" 	visible
		
		set "bb_mgmtApproverL2_group" 	visible
		set "bb_mgmtApproverL2_status" 	visible
		set "bb_mgmtApproverL2_remark" 	visible
		set "bb_mgmtApproverL2" 		visible
		set "bb_mgmtApproverL2_date" 	visible
		set "bb_mgmtApprover_orgunit"	visible
		
		set "bb_implApproverL1_group" 	visible
		set "bb_implApproverL1_aware" 	visible
		set "bb_implApproverL1" 		visible
		set "bb_implApproverL1_date" 	visible
		set "bb_implApprover_orgunit"	visible
		
		set "remark"                  	visible
		set "priority"                	visible
		set "bb_issueGrade"           	visible
		set "bb_faultLogCategory"     	visible
		set "immediateMeasure"        	visible
		set "bb_anotherImportantInfo" 	visible
		set "bb_confidentialityLevel" 	visible
		
		set "owners" 					invisible
		set "owner" 					invisible
		set "reviewers" 				invisible
		set "reviewer" 					invisible
		
		add object "information" message "info.issuemanagement.execution.phase.not.needed.INF"
		
		########################
		### BB CUSTOMIZATION ###
		set "issueRelevantObjects"    	mandatory
		
end

########################
### BB CUSTOMIZATION ###
# rule engine needs to be executed when the attribute value of "bb_issueType" is changed.
rule "bb_issueType set to 'faultlog' and bb_mgmtApproverL1_status set to 'please_select' --> hide approver attributes for creator [I,V]"

	salience 1900
	no-loop true

	when
	    # during creation the issue manager has the same rights as the creator
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "faultlog"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_mgmtApproverL1_status" 	invisible
		set "bb_mgmtApproverL1_remark" 	invisible
		set "bb_mgmtApproverL1" 		invisible
		set "bb_mgmtApproverL1_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
# rule engine needs to be executed when the attribute value of "bb_issueType" is changed.
rule "bb_issueType set to 'faultlog' and bb_mgmtApproverL1_status set to 'please_select' and bb_mgmtApproverL2_status contains not 'please_select' --> hide approver attributes for creator [I,V]"

	salience 1800
	no-loop true

	when
	    # during creation the issue manager has the same rights as the creator
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "faultlog"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL1_status" "CONTAINS" value "please_select"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL2_status" "CONTAINS NOT" value "please_select"

	then
		
		set "bb_mgmtApproverL1_status" 	visible
		set "bb_mgmtApproverL1_remark" 	visible
		
end

########################
### BB CUSTOMIZATION ###
# rule engine needs to be executed when the attribute value of "bb_issueType" is changed.
rule "bb_issueType set to 'faultlog' and bb_mgmtApproverL1_status contains not 'please_select' and bb_mgmtApproverL2_status set to 'please_select' --> hide approver attributes for creator [I,V]"

	salience 1800
	no-loop true

	when
	    # during creation the issue manager has the same rights as the creator
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "faultlog"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL1_status" "CONTAINS NOT" value "please_select"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_mgmtApproverL2_status" 	visible
		set "bb_mgmtApproverL2_remark" 	visible
		
end

########################
### BB CUSTOMIZATION ###
# rule engine needs to be executed when the attribute value of "bb_issueType" is changed.
rule "bb_issueType set to 'faultlog' and bb_mgmtApproverL2_status set to 'please_select' --> hide approver attributes for creator [I,V]"

	salience 1900
	no-loop true

	when
	    # during creation the issue manager has the same rights as the creator
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "faultlog"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_mgmtApproverL2_status" 	invisible
		set "bb_mgmtApproverL2_remark" 	invisible
		set "bb_mgmtApproverL2" 		invisible
		set "bb_mgmtApproverL2_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
# rule engine needs to be executed when the attribute value of "bb_issueType" is changed.
rule "bb_issueType set to 'faultlog' and bb_implApproverL1_status set to 'please_select' --> hide approver attributes for creator [I,V]"

	salience 1900
	no-loop true

	when
	    # during creation the issue manager has the same rights as the creator
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "faultlog"
		value comparison fulfilled: ":transient:" attr_value "bb_implApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_implApproverL1_aware" 	invisible
		set "bb_implApproverL1" 		invisible
		set "bb_implApproverL1_date" 	invisible
		
end
