package ISSUE_MGMTAPPL2_FAULTLOG_RuleSet
expander issue.dsl

import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelper;

##########################################################
### Workflow state "openForCreationFaultLogMgmtApprL2" ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'faultlog' and the ISSUE state is pending approval by mgmtApproverL2 [I,V]"

	salience 2000
	no-loop true

	when
		is in workflow state "openForCreationFaultLogMgmtApprL2" 
		( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" ) 
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "faultlog"

	then
		
		set "bb_mgmtApproverL2_status" 	editable
		set "bb_mgmtApproverL2_remark" 	editable
		
		set "bb_mgmtApproverL2_status" 	mandatory
		
end

########################
### BB CUSTOMIZATION ###
rule "ISSUE has been rejected by the mgmtApproverL2 --> 'bb_mgmtApproverL2_remark' is mandatory [I,V]"

	salience 2000
	no-loop true

	when
		is in workflow state "openForCreationFaultLogMgmtApprL2" 
		( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL2_status" "CONTAINS" value "rejected"

	then
		
		set "bb_mgmtApproverL2_remark" 	mandatory
end

###############################################
### All workflow states - after state rules ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'faultlog' --> attributes for issuemgmtapproverl2 [I,V]"

	salience 2000
	no-loop true

	when
		( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "faultlog"

	then
		
		set "bb_mgmtApproverL1_group" 	visible
		set "bb_mgmtApproverL1_status" 	visible
		set "bb_mgmtApproverL1_remark" 	visible
		set "bb_mgmtApproverL1" 		visible
		set "bb_mgmtApproverL1_date" 	visible
		
		set "bb_mgmtApproverL2_group" 	visible
		set "bb_mgmtApproverL2_status" 	visible
		set "bb_mgmtApproverL2_remark" 	visible
		set "bb_mgmtApproverL2" 		visible
		set "bb_mgmtApproverL2_date" 	visible
		set "bb_mgmtApprover_orgunit"	visible
		
		set "bb_implApproverL1_group" 	visible
		set "bb_implApproverL1_aware" 	visible
		set "bb_implApproverL1" 		visible
		set "bb_implApproverL1_date" 	visible
		set "bb_implApprover_orgunit"	visible
		
		set "remark"                  	visible
		set "priority"                	visible
		set "bb_issueGrade"           	visible
		set "bb_faultLogCategory"     	visible
		set "immediateMeasure"        	visible
		set "bb_anotherImportantInfo" 	visible
		set "bb_confidentialityLevel" 	visible
		
		set "owners" 					invisible
		set "owner" 					invisible
		set "reviewers" 				invisible
		set "reviewer" 					invisible
		
		add object "information" message "info.issuemanagement.execution.phase.not.needed.INF"
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'faultlog' and bb_mgmtApproverL1_status set to 'please_select' --> hide approver attributes for issuemgmtapproverl2 [I,V]"

	salience 1900
	no-loop true

	when
	    ( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "faultlog"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_mgmtApproverL1_status" 	invisible
		set "bb_mgmtApproverL1_remark" 	invisible
		set "bb_mgmtApproverL1" 		invisible
		set "bb_mgmtApproverL1_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
# rule engine needs to be executed when the attribute value of "bb_issueType" is changed.
rule "bb_issueType set to 'faultlog' and bb_mgmtApproverL1_status set to 'please_select' and bb_mgmtApproverL2_status contains not 'please_select' --> hide approver attributes for issuemgmtapproverl2 [I,V]"

	salience 1800
	no-loop true

	when
	    ( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "faultlog"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL1_status" "CONTAINS" value "please_select"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL2_status" "CONTAINS NOT" value "please_select"

	then
		
		set "bb_mgmtApproverL1_status" 	visible
		set "bb_mgmtApproverL1_remark" 	visible
		
end

########################
### BB CUSTOMIZATION ###
# rule engine needs to be executed when the attribute value of "bb_issueType" is changed.
rule "bb_issueType set to 'faultlog' and bb_mgmtApproverL1_status contains not 'please_select' and bb_mgmtApproverL2_status set to 'please_select' --> hide approver attributes for issuemgmtapproverl2 [I,V]"

	salience 1800
	no-loop true

	when
	    ( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "faultlog"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL1_status" "CONTAINS NOT" value "please_select"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_mgmtApproverL2_status" 	visible
		set "bb_mgmtApproverL2_remark" 	visible
		
end

########################
### BB CUSTOMIZATION ###
# rule engine needs to be executed when the attribute value of "bb_issueType" is changed.
rule "bb_issueType set to 'faultlog' and bb_mgmtApproverL2_status set to 'please_select' --> hide approver attributes for issuemgmtapproverl2 [I,V]"

	salience 1900
	no-loop true

	when
	    ( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "faultlog"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_mgmtApproverL2_status" 	invisible
		set "bb_mgmtApproverL2_remark" 	invisible
		set "bb_mgmtApproverL2" 		invisible
		set "bb_mgmtApproverL2_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
# rule engine needs to be executed when the attribute value of "bb_issueType" is changed.
rule "bb_issueType set to 'faultlog' and bb_implApproverL1_status set to 'please_select' --> hide approver attributes for issuemgmtapproverl2 [I,V]"

	salience 1900
	no-loop true

	when
	    ( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "faultlog"
		value comparison fulfilled: ":transient:" attr_value "bb_implApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_implApproverL1_aware" 	invisible
		set "bb_implApproverL1" 		invisible
		set "bb_implApproverL1_date" 	invisible
		
end
