package ISSUE_FAULTLOG_IRO_RuleSet
expander issue.dsl

import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelper;
import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelperBB;
import com.idsscheer.webapps.arcm.bl.component.issuemanagement.re.IssueHelperBB;

rule "IRO visible attributes - 'faultlog' [I,V]"

	salience 10
	no-loop true
	
	when
		is IRO
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "faultlog"		
				
	then
		set object readonly
		remove object messages	

		set "bb_mgmtApproverL1_group" 	visible
		set "bb_mgmtApproverL1_status" 	visible
		set "bb_mgmtApproverL1_remark" 	visible
		set "bb_mgmtApproverL1" 		visible
		set "bb_mgmtApproverL1_date" 	visible
		
		set "bb_mgmtApproverL2_group" 	visible
		set "bb_mgmtApproverL2_status" 	visible
		set "bb_mgmtApproverL2_remark" 	visible
		set "bb_mgmtApproverL2" 		visible
		set "bb_mgmtApproverL2_date" 	visible
		set "bb_mgmtApprover_orgunit"	visible
		
		set "bb_implApproverL1_group" 	visible
		set "bb_implApproverL1_aware" 	visible
		set "bb_implApproverL1" 		visible
		set "bb_implApproverL1_date" 	visible
		set "bb_implApprover_orgunit"	visible
		
		set "remark"                  	visible
		set "priority"                	visible
		set "bb_issueGrade"           	visible
		set "bb_faultLogCategory"     	visible
		set "immediateMeasure"        	visible
		set "bb_anotherImportantInfo" 	visible
		set "bb_confidentialityLevel" 	visible

end
