package CONTROL_RuleSet
expander control.dsl

import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelper;
import com.idsscheer.webapps.arcm.bl.component.testmanagement.re.ControlHelper;
import com.idsscheer.webapps.arcm.bl.component.testmanagement.re.ControlHelperBB

# OBJECT  client_objid       LONG       Client ID                                                                                                                                        
# OBJECT  client_sign        CLIENTSIGN Client                                                                                                                                           
# OBJECT  create_date        DATE       Creation date                                                                                                                                    
# OBJECT  creator_user_id    LONG       User ID (creator)                                                                                                                                
# OBJECT  delete_date        DATE       Deletion date                                                                                                                                    
# OBJECT  guid               STRING     GUID                                                                                                                                             
# OBJECT  obj_id             LONG       ID                                                                                                                                               
# OBJECT  obj_type           OBJECTTYPE Object type                                                                                                                                      
# OBJECT  root_guid          STRING     Root GUID                                                                                                                                        
# OBJECT  versions           LONG       Number of versions                                                                                                                               
# VERSION aris_change_date   DATE       ARIS change date                                                                                                                                 
# VERSION change_date        DATE       Change date                                                                                                                                      
# VERSION change_type        ENUM       Change type                changetype (created=0,unchanged=1,changed=2,deleted=3,xmlcreated=4,xmlchanged=5,xmldeleted=6)                         
# VERSION change_user_id     LONG       User ID (editor)                                                                                                                                 
# VERSION deactivated        BOOLEAN    Deactivated                                                                                                                                      
# VERSION id                 LONG       ID                                                                                                                                               
# VERSION substitute_user_id LONG       User ID (substitute)                                                                                                                             
# VERSION version_active     BOOLEAN    Current version                                                                                                                                  
# VERSION version_number     LONG       Version number                                                                                                                                   
# CONTROL control_effect     ENUM       Effect of control          controleffect (all=-1,unspecified=0,preventive=1,revealing=2)                                                         
# CONTROL control_execution  ENUM       Control execution          controlexecution (manual=1,it=2)                                                                                      
# CONTROL control_frequency  ENUM       Control frequency (target) controlfrequency (all=-1,unspecified=0,daily=1,weekly=2,monthly=3,quarterly=4,semiannually=5,annually=6,eventdriven=7)
# CONTROL control_id         STRING     Control ID                                                                                                                                       
# CONTROL control_objective  TEXT       Control objective                                                                                                                                
# CONTROL control_type       ENUM       COSO component             controltype (environment=1,risk_assessment=2,activity=3,information=4,monitoring=5)                                   
# CONTROL controls           TEXT       Control activities                                                                                                                               
# CONTROL key_control        BOOLEAN    Key control                                                                                                                                      
# CONTROL manager_group      LIST       Control manager            to 1 USERGROUP (LT=13)                                                                                                
# CONTROL name               STRING     Name                                                                                                                                             
# CONTROL testdefinitions    LIST       Test definitions           to * TESTDEFINITIONs (LT=15)                                                                                          

# DO NOT CHANGE THE LINES ABOVE - all of them will be updated automatically by tool com.idsscheer.webapps.arcm.bl.re.RETemplater

################################################
### All workflow states - before state rules ###

rule "mandatory fields control manager level client [I,V]"

    salience 10000

    when
        usergroup "controlmanager" has level "client"

    then
        set "manager_group"       		mandatory
        set "bb_evidenciasControle"		not_mandatory
		set "bb_salvaAtivos"			not_mandatory
		set "bb_controleAntifraude"		not_mandatory
		set "bb_conformidade"			not_mandatory
		set "bb_riscoFalha"				not_mandatory
end

rule "define all standard attributes editable [I,V]"

	salience 10100
	when

	then
		set "control_objective"   		editable
		set "controls"            		readonly
		
		set "testdefinitions"     		editable
		set "controlexecutiontasks"     editable
		
		########################
		### BB CUSTOMIZATION ###
		set "bb_afirmacoesControle"		editable
		set "bb_controlAssertions"		editable
		#set "bb_appSystems"		  	editable
		
		set "bb_nivelControle"			readonly		
		set "bb_conformidade"			editable
		set "bb_planilhaDept"           editable
		
		set "name"                		readonly
		set "key_control"         		readonly
		set "control_type"        		readonly
		set "control_execution"   		readonly
		set "control_effect"      		readonly
		set "control_frequency"   		readonly
		set "control_id"          		readonly
		set "bb_processoControle"       readonly
		set "bb_evidenciasControle"		editable
		set "bb_riscoFalha"				editable
		set "bb_riskfactor"             readonly
		
		
end

########################
### BB CUSTOMIZATION ###
rule "mark mandatory fields by role [I,V]"

	salience 10200

	when 	        
	     ( user has in_general role "controlmanager" OR
           user has in_general role "testmanager" )

	then

		set "bb_salvaAtivos"			editable
		set "bb_controleAntifraude"		editable		
		set "manager_group"       		editable		
		
    	set "bb_controleAntifraude" 	mandatory
    	set "bb_salvaAtivos"        	mandatory
    	set "manager_group"				mandatory
end    

rule "mark mandatory fields [I,V]"

	salience 10200
	no-loop true

	when 	

	then
		
		#set "controls"          	mandatory
		set "control_effect"    	mandatory
		set "control_frequency" 	mandatory
		set "name"              	mandatory
		
		########################
		### BB CUSTOMIZATION ###		
		#set "key_control"       	 mandatory
		#set "control_execution" 	 mandatory
		set "bb_conformidade"		 mandatory
		set "bb_evidenciasControle"  mandatory
		set "bb_riscoFalha"          mandatory

end

rule "object specific control manager cannot change control manager group assignment [I,V]"

    salience 10000
    no-loop true

    when
        user is ":persistent:" member of group in list "manager_group" AND
        usergroup "controlmanager" has_not level "client"

    then
        set "manager_group"       readonly

end