package INTERNALMESSAGE_RuleSet
expander internalmessage.dsl

import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelper;
import com.idsscheer.webapps.arcm.bl.component.administration.re.InternalmessageHelper;

# OBJECT          client_objid       LONG       Client ID             
# OBJECT          client_sign        CLIENTSIGN Client                
# OBJECT          create_date        DATE       Creation date         
# OBJECT          creator_user_id    LONG       User ID (creator)     
# OBJECT          delete_date        DATE       Deletion date         
# OBJECT          guid               STRING     GUID                  
# OBJECT          obj_id             LONG       ID                    
# OBJECT          obj_type           OBJECTTYPE Object type           
# OBJECT          root_guid          STRING     Root GUID             
# OBJECT          versions           LONG       Number of versions    
# VERSION         change_user_id     LONG       User ID (editor)      
# VERSION         deactivated        BOOLEAN    Deactivated           
# VERSION         id                 LONG       ID                    
# VERSION         substitute_user_id LONG       User ID (substitute)  
# VERSION         version_number     LONG       Version number        
# INTERNALMESSAGE archived           BOOLEAN    Archives              
# INTERNALMESSAGE body               TEXT       Message               
# INTERNALMESSAGE fromSender         LONG       Sender                
# INTERNALMESSAGE link               STRING     More...               
# INTERNALMESSAGE linkName           STRING     Link                  
# INTERNALMESSAGE sendDate           DATE       Sent date             
# INTERNALMESSAGE senderName         STRING     Sender                
# INTERNALMESSAGE subject            STRING     Subject               
# INTERNALMESSAGE toReceiver         LONG       Recipient             
# INTERNALMESSAGE unreaded           BOOLEAN    Read                  

# DO NOT CHANGE THE LINES ABOVE - all of them will be updated automatically by tool com.idsscheer.webapps.arcm.bl.re.RETemplater

#
# in order to enable DELETE button in BL
#
rule "mark artificial attribute editable [I,V]"

	salience 10100

	when

	then
		set "version_number" editable

end

rule "hide 'link' field if empty [I,V]"

    salience 10000

	when
        "link" is_not filled

	then
		set "link" invisible

end