package ISSUE_IMPLAPPL1_MANIFESTATION_RuleSet
expander issue.dsl

import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelper;

###############################################################
### Workflow state "openForCreationManifestationImplApprL1" ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'manifestation' and the ISSUE state is pending approval by implApproverL1 [I,V]"

	salience 2000
	no-loop true

	when
		is in workflow state "openForCreationManifestationImplApprL1" 
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" ) 
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "manifestation"

	then
		
		set "bb_implApproverL1_status" 	editable
		set "bb_implApproverL1_remark" 	editable
		
end

########################
### BB CUSTOMIZATION ###
rule "ISSUE has been rejected by the implApproverL1 and workflow state is 'openForCreationManifestationImplApprL1' --> 'bb_implApproverL1_remark' is mandatory [I,V]"

	salience 2000
	no-loop true

	when
		is in workflow state "openForCreationManifestationImplApprL1" 
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_implApproverL1_status" "CONTAINS" value "rejected"

	then
		
		set "bb_implApproverL1_remark" 	mandatory
end

###############################################
### All workflow states - after state rules ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'manifestation' --> attributes for issueimplapproverl1 [I,V]"

	salience 2000
	no-loop true

	when
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "manifestation"

	then
		
		set "bb_mgmtApproverL1_group" 	visible
		set "bb_mgmtApproverL1_aware" 	visible
		set "bb_mgmtApproverL1" 		visible
		set "bb_mgmtApproverL1_date" 	visible
		set "bb_mgmtApprover_orgunit"	visible
		
		set "bb_implApproverL1_group" 	visible
		set "bb_implApproverL1_status" 	visible
		set "bb_implApproverL1_remark" 	visible
		set "bb_implApproverL1" 		visible
		set "bb_implApproverL1_date" 	visible
		set "bb_implApprover_orgunit"	visible
		
		set "remark"                  	visible
		set "immediateMeasure"        	visible
		set "bb_anotherImportantInfo" 	visible
		set "bb_confidentialityLevel" 	visible
		
		set "owners" 					invisible
		set "owner" 					invisible
		set "reviewers" 				invisible
		set "reviewer" 					invisible
		
		add object "information" message "info.issuemanagement.execution.phase.not.needed.INF"
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'manifestation' and bb_implApproverL1_status set to 'please_select' --> hide approver attributes for issueimplapproverl1 [I,V]"

	salience 1900
	no-loop true

	when
	    ( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "manifestation"
		value comparison fulfilled: ":transient:" attr_value "bb_implApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_implApproverL1_status" 	invisible
		set "bb_implApproverL1_remark" 	invisible
		set "bb_implApproverL1" 		invisible
		set "bb_implApproverL1_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'manifestation' and bb_mgmtApproverL1_status set to 'please_select' --> hide approver attributes for issueimplapproverl1 [I,V]"

	salience 1900
	no-loop true

	when
	    ( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "manifestation"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_mgmtApproverL1_aware" 	invisible
		set "bb_mgmtApproverL1" 		invisible
		set "bb_mgmtApproverL1_date" 	invisible
		
end
