package ISSUE_EXECOWNERS_ACTION_RuleSet
expander issue.dsl

import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelper;
import com.idsscheer.webapps.arcm.bl.component.issuemanagement.re.IssueHelperBB;

########################################################
### Workflow state "openForExecution" ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and workflow state is 'openForExecution' --> attributes for owners [I,V]"

	salience 2000
	no-loop true

	when
	    is in workflow state "openForExecution"
		user is ":persistent:" member of group in list "bb_owners_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action" 

	then
		
		set "owner_status" 				editable
		set "bb_conclusionPercentage" 	editable
		set "bb_injuredIssue" 			editable
		set "bb_implDocuments" 			editable
		
		set "bb_conclusionPercentage" 	mandatory
		set "bb_injuredIssue" 			mandatory
		set "bb_implDocuments" 			mandatory
		
		
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and workflow state is 'openForExecution' and bb_injuredIssue is 'true' --> owner_remark is mandatory [I,V]"

	salience 2000
	no-loop true

	when
	    is in workflow state "openForExecution"
		user is ":persistent:" member of group in list "bb_owners_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action" 
		value comparison fulfilled: ":transient:" attr_value "bb_injuredIssue" "EQUALS" value "true"

	then
		
		set "owner_remark" 				visible
		
		set "owner_remark" 				editable
		
		set "owner_remark" 				mandatory
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and workflow state is 'openForExecution' and owner_status set to 'finished' --> check bb_conclusionPercentage [I,V]"

	salience 2000
	no-loop true

	when
	    is in workflow state "openForExecution"
		user is ":persistent:" member of group in list "bb_owners_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action" 
		value comparison fulfilled: ":transient:" attr_value "owner_status" "CONTAINS" value "finished"
		value comparison fulfilled: ":transient:" attr_value "bb_conclusionPercentage" "CONTAINS NOT" value "hundred"

	then
		
		set "bb_conclusionPercentage" invalid
		add "error" message "error.issue.owner.state.not.allowed.ERR" to "bb_conclusionPercentage"
		
end

###############################################
### All workflow states - after state rules ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' or 'action' --> readonly attributes for owners [I,V]"

	salience 2000
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_owners_group"
		( value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation" OR
		  value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action" )

	then
		
		set "bb_mgmtApproverL1_group" 		visible
		set "bb_mgmtApproverL1_status" 		visible
		set "bb_mgmtApproverL1_remark" 		visible
		set "bb_mgmtApproverL1" 			visible
		
		set "bb_mgmtApproverL2_group" 		visible
		set "bb_mgmtApprover_orgunit"		visible
		
		set "bb_implApproverL1_group" 		visible
		set "bb_implApproverL1_status" 		visible
		set "bb_implApproverL1_remark" 		visible
		set "bb_implApproverL1" 			visible
		
		set "bb_implApproverL2_group" 		visible
		set "bb_implApproverL2_status" 		visible
		set "bb_implApproverL2_remark" 		visible
		set "bb_implApproverL2" 			visible
		set "bb_implApprover_orgunit"		visible

		set "owner_status" 					visible
		
		set "bb_execImplApprL1_status" 		visible
		set "bb_execImplApprL1_remark"		visible
		set "bb_execImplApprL1"				visible
		
		set "bb_execImplApprL2_status" 		visible
		set "bb_execImplApprL2_remark"		visible
		set "bb_execImplApprL2"				visible
		
		set "bb_execMgmtApprL1_remark" 		visible
		set "bb_execMgmtApprL1" 			visible
		set "bb_execMgmtApprL1_status" 		visible
		
		set "bb_execMgmtApprL2_remark" 		visible
		set "bb_execMgmtApprL2" 			visible
		set "bb_execMgmtApprL2_status" 		visible
				
		set "bb_isTechSupportNeeded" 		visible
		set "remark"                  		visible
		set "priority"                		visible
		set "immediateMeasure"        		visible
		set "bb_firstPlannedEndDate" 		visible
		set "plannedenddate"          		visible
		set "bb_anotherImportantInfo" 		visible
		set "bb_confidentialityLevel" 		visible
		set "bb_projectServiceRequest" 		visible
		set "bb_conclusionPercentage" 		visible
		set "bb_injuredIssue" 				visible
		set "bb_implDocuments" 				visible
		set "bb_start_date"					visible
		
		set "bb_issueOrign"					visible
		
		## BdB CUSTOMIZATION
		#
		set "owner_remark"                  visible            
        set "bb_owners_group"               visible
        set "owner"                         visible
        set "reviewer_status"               visible
        set "reviewer_remark"               visible
        set "bb_reviewers_group"            visible
        set "reviewer"                      visible
        
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and 'bb_isTechSupportNeeded' equals 'true' --> readonly attributes for owners [I,V]"

	salience 2000
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_owners_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action" 
		value comparison fulfilled: ":transient:" attr_value "bb_isTechSupportNeeded" "EQUALS" value "true"

	then
		
		set "bb_techApproverL1_group" 		visible
		set "bb_techApproverL1_status" 		visible
		set "bb_techApproverL1_remark" 		visible
		set "bb_techApproverL1" 			visible
		
		set "bb_techApproverL2_group" 		visible
		set "bb_techApproverL2_status" 		visible
		set "bb_techApproverL2_remark" 		visible
		set "bb_techApproverL2" 			visible
		set "bb_techApprover_orgunit" 		visible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execImplApprL1_status set to 'please_select' --> hide approver attributes for owners [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_owners_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_execImplApprL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execImplApprL1_status" 	invisible
		set "bb_execImplApprL1_remark" 	invisible
		set "bb_execImplApprL1" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execImplApprL2_status set to 'please_select' --> hide approver attributes for owners [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_owners_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_execImplApprL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execImplApprL2_status" 	invisible
		set "bb_execImplApprL2_remark" 	invisible
		set "bb_execImplApprL2" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execMgmtApprL1_status set to 'please_select' --> hide approver attributes for owners [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_owners_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_execMgmtApprL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execMgmtApprL1_status" 	invisible
		set "bb_execMgmtApprL1_remark" 	invisible
		set "bb_execMgmtApprL1" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execMgmtApprL2_status set to 'please_select' --> hide approver attributes for owners [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_owners_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_execMgmtApprL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execMgmtApprL2_status" 	invisible
		set "bb_execMgmtApprL2_remark" 	invisible
		set "bb_execMgmtApprL2" 		invisible
		
end
########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and owner_status set to 'undecided' --> hide owner attributes for owners [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_owners_group"
		is in workflow state "openForExecution"		
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"		

	then
						
		set "owner"            				invisible	
end
########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and reviewer_status set to 'undecided' --> hide owner attributes for reviewers [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_owners_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"		
		value comparison fulfilled: ":transient:" attr_value "reviewer_status" "CONTAINS" value "undecided"

	then
		
		set "reviewer_status"            		invisible
		set "reviewer_remark"            		invisible
		set "reviewer"            				invisible	
end

