package ISSUE_MGMTAPPL2_ACTION_RuleSet
expander issue.dsl

import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelper;
import com.idsscheer.webapps.arcm.bl.component.issuemanagement.re.IssueHelperBB;


###############################################################
### Workflow state "openForReviewExecutableIssueMgmtApprL2" ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and workflow state is 'openForReviewExecutableIssueMgmtApprL2' --> attributes for issuemgmtapproverl2 [I,V]"

	salience 2000
	no-loop true

	when
	    is in workflow state "openForReviewExecutableIssueMgmtApprL2"
		( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action" 

	then
		
		set "bb_execMgmtApprL2_status" 		editable
		set "bb_execMgmtApprL2_remark" 		editable
		
end

########################
### BB CUSTOMIZATION ###
rule "ISSUE has been rejected by the mgmtApproverL2 workflow state is 'openForReviewExecutableIssueMgmtApprL2' --> 'bb_execMgmtApprL2_remark' is mandatory [I,V]"

	salience 2000
	no-loop true

	when
		is in workflow state "openForReviewExecutableIssueMgmtApprL2" 
		( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" ) 
		value comparison fulfilled: ":transient:" attr_value "bb_execMgmtApprL2_status" "CONTAINS" value "rejected"

	then
		
		set "bb_execMgmtApprL2_remark" 	mandatory
end


###############################################
### All workflow states - after state rules ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' or 'action' --> readonly attributes for issuemgmtapproverl2 [I,V]"

	salience 2000
	no-loop true

	when
		( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		( value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation" OR
		  value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action" )

	then
		
		set "bb_mgmtApproverL1_group" 		visible
		set "bb_mgmtApproverL1_status" 		visible
		set "bb_mgmtApproverL1_remark" 		visible
		set "bb_mgmtApproverL1" 			visible
		set "bb_mgmtApproverL1_date"		visible
		
		set "bb_mgmtApproverL2_group" 		visible
		set "bb_mgmtApproverL2_status" 		visible
		set "bb_mgmtApproverL2_remark" 		visible
		set "bb_mgmtApproverL2" 			visible
		set "bb_mgmtApproverL2_date"		visible
		set "bb_mgmtApprover_orgunit"		visible
		
		set "bb_implApproverL1_group" 		visible
		set "bb_implApproverL1_status" 		visible
		set "bb_implApproverL1_remark" 		visible
		set "bb_implApproverL1" 			visible
		set "bb_implApproverL1_date"		visible
		
		set "bb_implApproverL2_group" 		visible
		set "bb_implApproverL2_status" 		visible
		set "bb_implApproverL2_remark" 		visible
		set "bb_implApproverL2" 			visible
		set "bb_implApproverL2_date"		visible
		set "bb_implApprover_orgunit"		visible
		
		set "owner_status"            		visible
		set "owner_remark"            		visible
		
		set "bb_execImplApprL1_status" 		visible
		set "bb_execImplApprL1_remark"		visible
		set "bb_execImplApprL1"				visible
		
		set "bb_execImplApprL2_status" 		visible
		set "bb_execImplApprL2_remark"		visible
		set "bb_execImplApprL2"				visible
		
		set "bb_execMgmtApprL1_remark" 		visible
		set "bb_execMgmtApprL1" 			visible
		set "bb_execMgmtApprL1_status" 		visible
		
		set "bb_execMgmtApprL2_remark" 		visible
		set "bb_execMgmtApprL2" 			visible
		set "bb_execMgmtApprL2_status" 		visible
		
		set "bb_isTechSupportNeeded" 		visible
		set "remark"                  		visible
		set "priority"                		visible
		set "immediateMeasure"        		visible
		set "bb_firstPlannedEndDate" 		visible
		set "plannedenddate"          		visible
		set "bb_anotherImportantInfo" 		visible
		set "bb_confidentialityLevel" 		visible
		set "bb_projectServiceRequest" 		visible
		set "bb_conclusionPercentage" 		visible
		set "bb_injuredIssue" 				visible
		set "bb_implDocuments" 				visible
		set "bb_start_date"					visible
		
		set "bb_issueOrign"					visible
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' 'bb_isTechSupportNeeded' equals 'true' --> readonly attributes for issuemgmtapproverl2 [I,V]"

	salience 2000
	no-loop true

	when
		( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action" 
		value comparison fulfilled: ":transient:" attr_value "bb_isTechSupportNeeded" "EQUALS" value "true"

	then
		
		set "bb_techApproverL1_group" 		visible
		set "bb_techApproverL1_status" 		visible
		set "bb_techApproverL1_remark" 		visible
		set "bb_techApproverL1" 			visible
		
		set "bb_techApproverL2_group" 		visible
		set "bb_techApproverL2_status" 		visible
		set "bb_techApproverL2_remark" 		visible
		set "bb_techApproverL2" 			visible
		set "bb_techApprover_orgunit" 		visible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_mgmtApproverL1_status set to 'please_select' --> hide approver attributes for issuemgmtapproverl2 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_mgmtApproverL1_status" 	invisible
		set "bb_mgmtApproverL1_remark" 	invisible
		set "bb_mgmtApproverL1" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_mgmtApproverL2_status set to 'please_select' --> hide approver attributes for issuemgmtapproverl2 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_mgmtApproverL2_status" 	invisible
		set "bb_mgmtApproverL2_remark" 	invisible
		set "bb_mgmtApproverL2" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_implApproverL1_status set to 'please_select' --> hide approver attributes for issuemgmtapproverl2 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_implApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_implApproverL1_status" 	invisible
		set "bb_implApproverL1_remark" 	invisible
		set "bb_implApproverL1" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_techApproverL1_status set to 'please_select' --> hide approver attributes for issuemgmtapproverl2 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_techApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_techApproverL1_status" 	invisible
		set "bb_techApproverL1_remark" 	invisible
		set "bb_techApproverL1" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_techApproverL2_status set to 'please_select' --> hide approver attributes for issuemgmtapproverl2 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_techApproverL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_techApproverL2_status" 	invisible
		set "bb_techApproverL2_remark" 	invisible
		set "bb_techApproverL2" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_implApproverL2_status set to 'please_select' --> hide approver attributes for issuemgmtapproverl2 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_implApproverL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_implApproverL2_status" 	invisible
		set "bb_implApproverL2_remark" 	invisible
		set "bb_implApproverL2" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and owner_status contains not 'finished' --> hide owner attributes for issuemgmtapproverl2 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "owner_status" "CONTAINS NOT" value "finished"

	then
		
		set "owner_status"            		invisible
		set "owner_remark"            		invisible
		set "bb_conclusionPercentage" 		invisible
		set "bb_injuredIssue" 				invisible
		set "bb_implDocuments" 				invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execImplApprL1_status set to 'please_select' --> hide approver attributes for issuemgmtapproverl2 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_execImplApprL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execImplApprL1_status" 	invisible
		set "bb_execImplApprL1_remark" 	invisible
		set "bb_execImplApprL1" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execImplApprL2_status set to 'please_select' --> hide approver attributes for issuemgmtapproverl2 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_execImplApprL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execImplApprL2_status" 	invisible
		set "bb_execImplApprL2_remark" 	invisible
		set "bb_execImplApprL2" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execMgmtApprL1_aware set to 'false' --> hide approver attributes for issuemgmtapproverl2 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_execMgmtApprL1_aware" "EQUALS" value "false"

	then
		
		set "bb_execMgmtApprL1_status" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execMgmtApprL1_aware is_not filled --> hide approver attributes for issuemgmtapproverl2 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		( is in workflow state "openForReviewExecutableIssueMgmtApprL2" OR
		  is in workflow state "openForReviewExecutableIssueMgmtApprL1" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		"bb_execMgmtApprL1_aware" is_not filled

	then
		
		set "bb_execMgmtApprL1_status" 	visible
		set "bb_execMgmtApprL1_remark" 	visible
		set "bb_execMgmtApprL1" 		visible
		set "bb_execMgmtApprL1_aware" 	visible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execMgmtApprL2_status set to 'please_select' --> hide approver attributes for issuemgmtapproverl2 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issuemgmtapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_execMgmtApprL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execMgmtApprL2_status" 	invisible
		set "bb_execMgmtApprL2_remark" 	invisible
		set "bb_execMgmtApprL2" 		invisible
		
end
