package ISSUE_ACTION_RuleSet
expander issue.dsl

import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelper;
import com.idsscheer.webapps.arcm.bl.component.issuemanagement.re.IssueHelperBB;

#######################################################
### Workflow state "openForCreation" ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' --> set workflow actors mandatory for creator [I,V]"

	salience 2000
	no-loop true

	when
	    ( is in workflow state "PREPARED" OR
		  is in workflow state "openForCreation" )
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"

	then
		
		set "bb_mgmtApproverL1_group" 		editable
		set "bb_mgmtApproverL2_group" 		editable
		set "bb_mgmtApprover_orgunit" 		editable
		#set "owners"            	   		editable
		#set "reviewers"            		editable
		set "remark"                  		editable
		set "priority"                		editable
		set "immediateMeasure"        		editable
		set "plannedenddate"          		editable
		set "bb_anotherImportantInfo" 		editable
		set "bb_confidentialityLevel" 		editable
		set "bb_projectServiceRequest" 		editable
		set "bb_owners_group" 				editable
		set "bb_reviewers_group" 			editable
		set "bb_start_date"					editable
		
		set "bb_mgmtApproverL1_group" 		mandatory
		set "bb_mgmtApproverL2_group" 		mandatory
		set "bb_isTechSupportNeeded" 		mandatory
		set "priority"                		mandatory
		set "plannedenddate"          		mandatory
		set "bb_confidentialityLevel" 		mandatory
		set "bb_start_date"					mandatory
		
		execute action rules
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' --> 'bb_start_date' must not be more than today [I,V]"

	salience 2000
	no-loop true

	when
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		"bb_start_date" is dirty
		"bb_start_date" is filled
		value comparison fulfilled: ":transient:" attr_value "bb_start_date" "GREATER THAN" value ":TODAY:"

	then
		set "bb_start_date" invalid
		add "error" message "issue.start.date.not.after.today.ERR" to "bb_start_date"

end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' --> can creator group delegate issues [I,V]"

	salience 2000
	no-loop true

	when
	    ( is in workflow state "PREPARED" OR
		  is in workflow state "openForCreation" )
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		#can creator group delegate issues
		
	then
		
		set "bb_implApproverL1_group" 		editable
		set "bb_implApproverL2_group" 		editable
		set "bb_implApprover_orgunit" 		editable
		
		set "bb_implApproverL1_group" 		mandatory
		set "bb_implApproverL2_group" 		mandatory
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and creator_status set to 'released' --> set workflow fields mandatory for creator [I,V]"

	salience 2000
	no-loop true

	when
	    ( is in workflow state "PREPARED" OR
		  is in workflow state "openForCreation" )
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "creator_status" "CONTAINS" value "released"

	then
		
		
		########################
		### BB CUSTOMIZATION ###
		#set "owners"                   mandatory
		#set "reviewers"                mandatory
		set "bb_owners_group" 			mandatory
		set "bb_reviewers_group" 		mandatory
		
		#execute action rules
		
end

###############################################
### All workflow states - after state rules ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' --> attributes for creator [I,V]"

	salience 2000
	no-loop true

	when
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"

	then
		
		set "bb_mgmtApproverL1_group" 		visible
		set "bb_mgmtApproverL1_status" 		visible
		set "bb_mgmtApproverL1_remark" 		visible
		set "bb_mgmtApproverL1" 			visible
		set "bb_mgmtApproverL1_date"		visible
		
		set "bb_mgmtApproverL2_group" 		visible
		set "bb_mgmtApproverL2_status" 		visible
		set "bb_mgmtApproverL2_remark" 		visible
		set "bb_mgmtApproverL2" 			visible
		set "bb_mgmtApproverL2_date"		visible
		set "bb_mgmtApprover_orgunit"		visible
		
		set "bb_implApproverL1_group" 		visible
		set "bb_implApproverL1_status" 		visible
		set "bb_implApproverL1_remark" 		visible
		set "bb_implApproverL1" 			visible
		set "bb_implApproverL1_date"		visible
		
		set "bb_implApproverL2_group" 		visible
		set "bb_implApproverL2_status" 		visible
		set "bb_implApproverL2_remark" 		visible
		set "bb_implApproverL2" 			visible
		set "bb_implApproverL2_date"		visible
		set "bb_implApprover_orgunit"		visible
		
		set "owner_status"            		visible
		set "owner_remark"            		visible
		set "bb_execImplApprL1_status" 		visible
		set "bb_execImplApprL1_remark"		visible
		set "bb_execImplApprL1"				visible
		set "bb_execImplApprL2_status" 		visible
		set "bb_execImplApprL2_remark"		visible
		set "bb_execImplApprL2"				visible
		set "reviewer_status"            	visible
		set "reviewer_remark"            	visible
		set "bb_execMgmtApprL1_status" 		visible
		set "bb_execMgmtApprL1_remark" 		visible
		set "bb_execMgmtApprL1" 			visible
		set "bb_execMgmtApprL1_aware" 		visible
		set "bb_execMgmtApprL2_status" 		visible
		set "bb_execMgmtApprL2_remark" 		visible
		set "bb_execMgmtApprL2" 			visible
		
		set "bb_owners_group" 				visible
		set "bb_reviewers_group" 			visible
		
		set "bb_isTechSupportNeeded" 		visible
		set "remark"                  		visible
		set "priority"                		visible
		set "immediateMeasure"        		visible
		set "bb_firstPlannedEndDate" 		visible
		set "plannedenddate"          		visible
		set "bb_anotherImportantInfo" 		visible
		set "bb_confidentialityLevel" 		visible
		set "bb_projectServiceRequest" 		visible
		set "bb_conclusionPercentage" 		visible
		set "bb_injuredIssue" 				visible
		set "bb_implDocuments" 				visible
		set "bb_start_date"					visible
		
		set "bb_issueOrign"					visible	
		
		## BdB CUSTOMIZATION
		#
        set "owner"                         visible
        set "reviewer"                      visible
		
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and 'bb_isTechSupportNeeded' equals 'true' --> attributes for creator [I,V]"

	salience 2000
	no-loop true

	when
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_isTechSupportNeeded" "EQUALS" value "true"

	then
		
		set "bb_techApproverL1_group" 		visible
		set "bb_techApproverL1_status" 		visible
		set "bb_techApproverL1_remark" 		visible
		set "bb_techApproverL1" 			visible
		set "bb_techApproverL1_date" 		visible
		
		set "bb_techApproverL2_group" 		visible
		set "bb_techApproverL2_status" 		visible
		set "bb_techApproverL2_remark" 		visible
		set "bb_techApproverL2" 			visible
		set "bb_techApproverL2_date" 		visible
		set "bb_techApprover_orgunit" 		visible
		
		set "bb_techApprover_orgunit" 		editable
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and 'bb_isTechSupportNeeded' equals 'false' --> attributes for creator [I,V]"

	salience 2000
	no-loop true

	when
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_isTechSupportNeeded" "EQUALS" value "false"

	then
		
		reset "bb_techApprover_orgunit" to default_value
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_mgmtApproverL1_status set to 'please_select' --> hide approver attributes [I,V]"

	salience 1900
	no-loop true

	when
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_mgmtApproverL1_status" 	invisible
		set "bb_mgmtApproverL1_remark" 	invisible
		set "bb_mgmtApproverL1" 		invisible
		set "bb_mgmtApproverL1_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_mgmtApproverL2_status set to 'please_select' --> hide approver attributes [I,V]"

	salience 1900
	no-loop true

	when
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_mgmtApproverL2_status" 	invisible
		set "bb_mgmtApproverL2_remark" 	invisible
		set "bb_mgmtApproverL2" 		invisible
		set "bb_mgmtApproverL2_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_implApproverL1_status set to 'please_select' --> hide approver attributes [I,V]"

	salience 1900
	no-loop true

	when
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_implApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_implApproverL1_status" 	invisible
		set "bb_implApproverL1_remark" 	invisible
		set "bb_implApproverL1" 		invisible
		set "bb_implApproverL1_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_techApproverL1_status set to 'please_select' --> hide approver attributes [I,V]"

	salience 1900
	no-loop true

	when
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_techApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_techApproverL1_status" 	invisible
		set "bb_techApproverL1_remark" 	invisible
		set "bb_techApproverL1" 		invisible
		set "bb_techApproverL1_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_techApproverL2_status set to 'please_select' --> hide approver attributes [I,V]"

	salience 1900
	no-loop true

	when
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_techApproverL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_techApproverL2_status" 	invisible
		set "bb_techApproverL2_remark" 	invisible
		set "bb_techApproverL2" 		invisible
		set "bb_techApproverL2_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_implApproverL2_status set to 'please_select' --> hide approver attributes [I,V]"

	salience 1900
	no-loop true

	when
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_implApproverL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_implApproverL2_status" 	invisible
		set "bb_implApproverL2_remark" 	invisible
		set "bb_implApproverL2" 		invisible
		set "bb_implApproverL2_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and owner_status contains not 'finished' --> hide owner attributes [I,V]"

	salience 1900
	no-loop true

	when
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		user is_not assigned in list "owners"  
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "owner_status" "CONTAINS NOT" value "finished"

	then
		
		set "owner_status"            		invisible
		set "owner_remark"            		invisible
		set "bb_conclusionPercentage" 		invisible
		set "bb_injuredIssue" 				invisible
		set "bb_implDocuments" 				invisible
		
		## BdB CUSTOMIZATION
		set "owner"                         invisible
		set "reviewer"                      invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execImplApprL1_status set to 'please_select' --> hide approver attributes [I,V]"

	salience 1900
	no-loop true

	when
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_execImplApprL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execImplApprL1_status" 	invisible
		set "bb_execImplApprL1_remark" 	invisible
		set "bb_execImplApprL1" 		invisible
		
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execImplApprL2_status set to 'please_select' --> hide approver attributes [I,V]"

	salience 1900
	no-loop true

	when
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_execImplApprL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execImplApprL2_status" 	invisible
		set "bb_execImplApprL2_remark" 	invisible
		set "bb_execImplApprL2" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and reviewer_status contains not 'approved' --> hide reviewer attributes [I,V]"

	salience 1900
	no-loop true

	when
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "reviewer_status" "CONTAINS" value "undecided"

	then
		
		set "reviewer_status"            	invisible
		set "reviewer_remark"            	invisible
		
		## BdB CUSTOMIZATION
		set "reviewer"                      invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execMgmtApprL1_aware is_not filled --> hide approver attributes [I,V]"

	salience 1900
	no-loop true

	when
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		"bb_execMgmtApprL1_aware" is_not filled

	then
		
		set "bb_execMgmtApprL1_status" 	invisible
		set "bb_execMgmtApprL1_remark" 	invisible
		set "bb_execMgmtApprL1" 		invisible
		set "bb_execMgmtApprL1_aware" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execMgmtApprL2_status set to 'please_select' --> hide approver attributes [I,V]"

	salience 1900
	no-loop true

	when
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_execMgmtApprL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execMgmtApprL2_status" 	invisible
		set "bb_execMgmtApprL2_remark" 	invisible
		set "bb_execMgmtApprL2" 		invisible
		
end

rule "hide owners attribute [I,V]"

	salience 1800
	no-loop true

	when
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
	then
		set "owners" 					invisible
		set "reviewers"                 invisible
end

rule "bb_issueType set to 'action' and bb_isTechSupportNeeded set to 'true' --> show bb_isTechSupportNeeded [I,V]"

	salience 1900
	no-loop true
	
	when
	    ( is in workflow state "PREPARED" OR
		  is in workflow state "openForCreation" )
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_isTechSupportNeeded" "EQUALS" value "true"

	then
		set "bb_isTechSupportNeeded" visible
		set "bb_isTechSupportNeeded" not_mandatory
		set "bb_isTechSupportNeeded" readonly
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and owner_status contains not 'undecided' --> show owner status attribute [I,V]"

	salience 1800
	no-loop true

	when
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "owner_status" "CONTAINS NOT" value "undecided"

	then
		
		set "owner_status"            		visible		
end
########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and reviewer_status contains not 'undecided' --> show reviewer status attribute [I,V]"

	salience 1800
	no-loop true

	when
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "reviewer_status" "CONTAINS NOT" value "undecided"

	then
		
		set "reviewer_status"            		visible		
end
