package ISSUE_IMPLAPPL1_ACTION_RuleSet
expander issue.dsl

import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelper;
import com.idsscheer.webapps.arcm.bl.component.issuemanagement.re.IssueHelperBB;

########################################################
### Workflow state "openForCreationActionImplApprL1" ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and workflow state is 'openForCreationActionImplApprL1' --> attributes for issueimplapproverl1 [I,V]"

	salience 2000
	no-loop true

	when
	    is in workflow state "openForCreationActionImplApprL1"
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"

	then
		
		set "bb_implApproverL1_status" 		editable
		set "bb_implApproverL1_remark" 		editable
		
end

########################
### BB CUSTOMIZATION ###
rule "ISSUE has been rejected by the implApproverL1 workflow state is 'openForCreationActionImplApprL1' --> 'bb_implApproverL1_remark' is mandatory [I,V]"

	salience 2000
	no-loop true

	when
		is in workflow state "openForCreationActionImplApprL1" 
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_implApproverL1_status" "CONTAINS" value "rejected"

	then
		
		set "bb_implApproverL1_remark" 	mandatory
end

########################
### BB CUSTOMIZATION ###
rule "ISSUE has been approved by the implApproverL1 workflow state is 'openForCreationActionImplApprL1' --> check specific rules [I,V]"

	salience 2000
	no-loop true

	when
		is in workflow state "openForCreationActionImplApprL1" 
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_implApproverL1_status" "CONTAINS" value "accepted"

	then
		
		execute action rules
end

##################################################################
### Workflow state "openForExecutionExecutableIssueImplApprL1" ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action'and workflow state is 'openForExecutionExecutableIssueImplApprL1' --> attributes for issueimplapproverl1 [I,V]"

	salience 2000
	no-loop true

	when
	    is in workflow state "openForExecutionExecutableIssueImplApprL1"
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"

	then
		
		set "bb_execImplApprL1_status" 		editable
		set "bb_execImplApprL1_remark" 		editable
		
end

########################
### BB CUSTOMIZATION ###
rule "ISSUE has been rejected by the implApproverL1 workflow state is 'openForExecutionExecutableIssueImplApprL1' --> 'bb_execImplApprL1_remark' is mandatory [I,V]"

	salience 2000
	no-loop true

	when
		is in workflow state "openForExecutionExecutableIssueImplApprL1" 
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_execImplApprL1_status" "CONTAINS" value "rejected"

	then
		
		set "bb_execImplApprL1_remark" 	mandatory
end


###############################################
### All workflow states - after state rules ###


########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' or 'tech_recommendation' --> readonly attributes for issueimplapproverl1 [I,V]"

	salience 2000
	no-loop true

	when
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		( value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action" OR
		  value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation" )

	then
		
		set "bb_mgmtApproverL1_group" 		visible 
		set "bb_mgmtApproverL1_status" 		visible
		set "bb_mgmtApproverL1_remark" 		visible
		set "bb_mgmtApproverL1" 			visible
		set "bb_mgmtApproverL1_date"		visible
		
		set "bb_mgmtApproverL2_group" 		visible
		set "bb_mgmtApproverL2_status" 		visible
		set "bb_mgmtApproverL2_remark" 		visible
		set "bb_mgmtApproverL2" 			visible
		set "bb_mgmtApproverL2_date"		visible
		set "bb_mgmtApprover_orgunit"		visible
		
		set "bb_implApproverL1_group" 		visible
		set "bb_implApproverL1_status" 		visible
		set "bb_implApproverL1_remark" 		visible
		set "bb_implApproverL1" 			visible
		set "bb_implApproverL1_date"		visible
		
		set "bb_implApproverL2_group" 		visible
		set "bb_implApproverL2_status" 		visible
		set "bb_implApproverL2_remark" 		visible
		set "bb_implApproverL2" 			visible
		set "bb_implApproverL2_date"		visible
		set "bb_implApprover_orgunit"		visible
		
		set "bb_isTechSupportNeeded" 		visible
		
		set "owner_status" 					visible
		set "owner_remark" 					visible
		set "bb_owners_group" 				visible
		set "owner" 						visible
		
		set "bb_execImplApprL1_status" 		visible
		set "bb_execImplApprL1_remark"		visible
		set "bb_execImplApprL1"				visible
		
		set "bb_execImplApprL2_status" 		visible
		set "bb_execImplApprL2_remark" 		visible
		set "bb_execImplApprL2"				visible
		
		set "reviewer_status"            	visible
		set "reviewer_remark"            	visible
		set "bb_reviewers_group" 			visible
		set "reviewer" 						visible
		
		set "bb_execMgmtApprL1_remark" 		visible
		set "bb_execMgmtApprL1" 			visible
		set "bb_execMgmtApprL1_status" 		visible
		
		set "bb_execMgmtApprL2_remark" 		visible
		set "bb_execMgmtApprL2" 			visible
		set "bb_execMgmtApprL2_status" 		visible
		
		set "remark"                  		visible
		set "priority"                		visible
		set "immediateMeasure"        		visible
		set "bb_firstPlannedEndDate" 		visible
		set "plannedenddate"          		visible
		set "bb_anotherImportantInfo" 		visible
		set "bb_confidentialityLevel" 		visible
		set "bb_projectServiceRequest" 		visible
		set "bb_conclusionPercentage" 		visible
		set "bb_injuredIssue" 				visible
		set "bb_implDocuments" 				visible
		set "bb_start_date"					visible
		
		set "bb_issueOrign"					visible
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and 'bb_isTechSupportNeeded' equals 'true' --> readonly attributes for issueimplapproverl1 [I,V]"

	salience 2000
	no-loop true

	when
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_isTechSupportNeeded" "EQUALS" value "true"

	then
		
		set "bb_techApproverL1_group" 		visible
		set "bb_techApproverL1_status" 		visible
		set "bb_techApproverL1_remark" 		visible
		set "bb_techApproverL1" 			visible
		set "bb_techApproverL1_date" 		visible
		
		set "bb_techApproverL2_group" 		visible
		set "bb_techApproverL2_status" 		visible
		set "bb_techApproverL2_remark" 		visible
		set "bb_techApproverL2" 			visible
		set "bb_techApproverL2_date" 		visible
		set "bb_techApprover_orgunit" 		visible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_mgmtApproverL1_status set to 'please_select' --> hide approver attributes for issueimplapproverl1 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_mgmtApproverL1_status" 	invisible
		set "bb_mgmtApproverL1_remark" 	invisible
		set "bb_mgmtApproverL1" 		invisible
		set "bb_mgmtApproverL1_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_mgmtApproverL2_status set to 'please_select' --> hide approver attributes for issueimplapproverl1 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_mgmtApproverL2_status" 	invisible
		set "bb_mgmtApproverL2_remark" 	invisible
		set "bb_mgmtApproverL2" 		invisible
		set "bb_mgmtApproverL2_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_implApproverL1_status set to 'please_select' --> hide approver attributes for issueimplapproverl1 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_implApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_implApproverL1_status" 	invisible
		set "bb_implApproverL1_remark" 	invisible
		set "bb_implApproverL1" 		invisible
		set "bb_implApproverL1_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_techApproverL1_status set to 'please_select' --> hide approver attributes for issueimplapproverl1 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_techApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_techApproverL1_status" 	invisible
		set "bb_techApproverL1_remark" 	invisible
		set "bb_techApproverL1" 		invisible
		set "bb_techApproverL1_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_techApproverL2_status set to 'please_select' --> hide approver attributes for issueimplapproverl1 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_techApproverL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_techApproverL2_status" 	invisible
		set "bb_techApproverL2_remark" 	invisible
		set "bb_techApproverL2" 		invisible
		set "bb_techApproverL2_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_implApproverL2_status set to 'please_select' --> hide approver attributes for issueimplapproverl1 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_implApproverL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_implApproverL2_status" 	invisible
		set "bb_implApproverL2_remark" 	invisible
		set "bb_implApproverL2" 		invisible
		set "bb_implApproverL2_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and owner_status set to 'undecided' --> hide owner attributes for issueimplapproverl1 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "owner_status" "CONTAINS" value "undecided"

	then
		
		set "owner_status"            		invisible
		set "owner_remark"            		invisible
		set "owner"            				invisible
		set "bb_conclusionPercentage" 		invisible
		set "bb_injuredIssue" 				invisible
		set "bb_implDocuments" 				invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execImplApprL1_status set to 'please_select' --> hide approver attributes for issueimplapproverl1 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_execImplApprL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execImplApprL1_status" 	invisible
		set "bb_execImplApprL1_remark" 	invisible
		set "bb_execImplApprL1" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execImplApprL2_status set to 'please_select' --> hide approver attributes for issueimplapproverl1 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_execImplApprL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execImplApprL2_status" 	invisible
		set "bb_execImplApprL2_remark" 	invisible
		set "bb_execImplApprL2" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and reviewer_status contains not 'approved' --> hide reviewer attributes for issueimplapproverl1 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "reviewer_status" "CONTAINS" value "undecided"


	then
		
		set "reviewer_status"            	invisible
		set "reviewer_remark"            	invisible
		set "reviewer"            			invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execMgmtApprL1_status set to 'please_select' --> hide approver attributes for issueimplapproverl1 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_execMgmtApprL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execMgmtApprL1_status" 	invisible
		set "bb_execMgmtApprL1_remark" 	invisible
		set "bb_execMgmtApprL1" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execMgmtApprL2_status set to 'please_select' --> hide approver attributes for issueimplapproverl1 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_execMgmtApprL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execMgmtApprL2_status" 	invisible
		set "bb_execMgmtApprL2_remark" 	invisible
		set "bb_execMgmtApprL2" 		invisible
		
end
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and workflow state is 'openForReview' --> hide reviewer attributes for issueimplapproverl1 [I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issueimplapproverl1" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		is in workflow state "openForReview"

	then
		
		set "reviewer_remark"            	invisible
		set "reviewer"            			invisible
		
end
