package ISSUE_EXECREVIEWERS_ACTION_RuleSet
expander issue.dsl

import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelper;
import com.idsscheer.webapps.arcm.bl.component.issuemanagement.re.IssueHelperBB;

#####################################################
### Workflow state "openForReview" ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and workflow state is 'openForReview' --> attributes for reviewers [I,V]"

	salience 2000
	no-loop true

	when
	    is in workflow state "openForReview"
		user is ":persistent:" member of group in list "bb_reviewers_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action" 

	then
		
		set "reviewer_status" 			editable
		set "reviewer_remark" 			editable
		
		set "reviewer_remark" 			mandatory
		
end

###############################################
### All workflow states - after state rules ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' or 'action' --> readonly attributes for reviewers [I,V]"

	salience 2000
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_reviewers_group"
		( value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation" OR
		  value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action" )

	then
		
		set "bb_mgmtApproverL1_group" 		visible
		set "bb_mgmtApproverL1_status" 		visible
		set "bb_mgmtApproverL1_remark" 		visible
		set "bb_mgmtApproverL1" 			visible
		
		set "bb_mgmtApproverL2_group" 		visible
		set "bb_mgmtApprover_orgunit"		visible
		
		set "bb_implApproverL1_group" 		visible
		set "bb_implApproverL1_status" 		visible
		set "bb_implApproverL1_remark" 		visible
		set "bb_implApproverL1" 			visible
		
		set "bb_implApproverL2_group" 		visible
		set "bb_implApproverL2_status" 		visible
		set "bb_implApproverL2_remark" 		visible
		set "bb_implApproverL2" 			visible
		set "bb_implApprover_orgunit"		visible

		set "owner_status" 					visible
		
		set "bb_execImplApprL1_status" 		visible
		set "bb_execImplApprL1_remark"		visible
		set "bb_execImplApprL1"				visible
		
		set "reviewer_status" 				visible
		set "reviewer_remark" 				visible
		
		set "bb_execMgmtApprL1_status" 		visible
		#set "bb_execMgmtApprL1_remark" 	visible
		#set "bb_execMgmtApprL1" 			visible
		#set "bb_execMgmtApprL1_aware" 		visible
				
		set "bb_isTechSupportNeeded" 		visible
		set "remark"                  		visible
		set "priority"                		visible
		set "immediateMeasure"        		visible
		set "bb_firstPlannedEndDate" 		visible
		set "plannedenddate"          		visible
		set "bb_anotherImportantInfo" 		visible
		set "bb_confidentialityLevel" 		visible
		set "bb_projectServiceRequest" 		visible
		set "bb_conclusionPercentage" 		visible
		set "bb_injuredIssue" 				visible
		set "bb_implDocuments" 				visible
		set "bb_start_date"					visible
		
		set "bb_issueOrign"					visible
		
		## BdB CUSTOMIZATION
		#
		set "owner_remark"                  visible            
        set "bb_owners_group"               visible
        set "owner"                         visible
        set "bb_reviewers_group"            visible
        set "reviewer"                      visible
        
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and 'bb_isTechSupportNeeded' equals 'true' --> readonly attributes for reviewers [I,V]"

	salience 2000
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_reviewers_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action" 
		value comparison fulfilled: ":transient:" attr_value "bb_isTechSupportNeeded" "EQUALS" value "true"

	then
		
		set "bb_techApproverL1_group" 		visible
		set "bb_techApproverL1_status" 		visible
		set "bb_techApproverL1_remark" 		visible
		set "bb_techApproverL1" 			visible
		
		set "bb_techApproverL2_group" 		visible
		set "bb_techApproverL2_status" 		visible
		set "bb_techApproverL2_remark" 		visible
		set "bb_techApproverL2" 			visible
		set "bb_techApprover_orgunit" 		visible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execImplApprL1_status set to 'please_select' --> hide approver attributes for reviewers [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_reviewers_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_execImplApprL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execImplApprL1_status" 	invisible
		set "bb_execImplApprL1_remark" 	invisible
		set "bb_execImplApprL1" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execImplApprL2_status set to 'please_select' --> hide approver attributes for reviewers [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_reviewers_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_execImplApprL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execImplApprL2_status" 	invisible
		set "bb_execImplApprL2_remark" 	invisible
		set "bb_execImplApprL2" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and reviewer_status contains not 'approved' --> hide reviewer attributes for reviewers [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_reviewers_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "reviewer_status" "CONTAINS" value "undecided"

	then
		
		set "reviewer_status"            	invisible
		set "reviewer_remark"            	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execMgmtApprL1_aware is_not filled --> hide approver attributes for reviewers [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_reviewers_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		"bb_execMgmtApprL1_aware" is filled

	then
		
		
		set "bb_execMgmtApprL1_remark" 	visible
		set "bb_execMgmtApprL1" 		visible
		set "bb_execMgmtApprL1_aware" 	visible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and bb_execMgmtApprL1_status set to 'please_select' --> hide approver attributes for reviewers [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_reviewers_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"
		value comparison fulfilled: ":transient:" attr_value "bb_execMgmtApprL1_status" "CONTAINS" value "please_select" 


	then
		
		set "bb_execMgmtApprL1_status" 	invisible		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'action' and workflow state is 'openForReview' --> hide reviewer attributes for reviewer [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_reviewers_group"
		is in workflow state "openForReview"		
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "action"		
	
	then	
		set "reviewer"            		invisible
		
end


