package ISSUE_IMPLAPPL2_EXTRAPOLATION_RuleSet
expander issue.dsl

import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelper;

###############################################################
### Workflow state "openForCreationExtrapolationImplApprL2" ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'extra_sheet' and workflow state is 'openForCreationExtrapolationImplApprL2' --> attributes for issueimplapproverl2 [I,V]"

	salience 2000
	no-loop true

	when
		is in workflow state "openForCreationExtrapolationImplApprL2" 
		( user has at object role "issueimplapproverl2" OR
		  user has in_general role "issuemanager" ) 
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "extra_sheet"

	then
		
		set "bb_implApproverL2_aware" 	editable
		
end

###############################################
### All workflow states - after state rules ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'extra_sheet' --> attributes for issueimplapproverl2 [I,V]"

	salience 2000
	no-loop true

	when
		( user has at object role "issueimplapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "extra_sheet"

	then
		
		set "bb_mgmtApproverL1_group" 	visible
		set "bb_mgmtApproverL1_status" 	visible
		set "bb_mgmtApproverL1_remark" 	visible
		set "bb_mgmtApproverL1" 		visible
		set "bb_mgmtApproverL1_date" 	visible
		set "bb_mgmtApprover_orgunit"	visible
		
		set "bb_implApproverL2_group" 	visible
		set "bb_implApproverL2_aware" 	visible
		set "bb_implApproverL2" 		visible
		set "bb_implApproverL2_date" 	visible
		set "bb_implApprover_orgunit"	visible
		
		#set "owners"            	   	visible
		#set "owner_status"            	visible
		#set "owner"            	   	visible
		#set "reviewers"            	visible
		#set "reviewer_status"          visible
		#set "reviewer_remark"          visible
		#set "reviewer"            		visible
		
		set "remark"                  	visible
		set "bb_specificKpiLimit" 		visible
		set "bb_specificKpiLimitAmount" visible
		set "bb_kpiLimitCurrentAmount" 	visible
		set "bb_specificKpiLimitDocs" 	visible
		set "plannedenddate"          	visible
		#set "immediateMeasure"        	visible
		
		set "remediationMeasure"		not_mandatory
		set "remediationMeasure"		invisible
		
		set "owners" 					invisible
		set "owner" 					invisible
		set "reviewers" 				invisible
		set "reviewer" 					invisible
		
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'extra_sheet' and bb_mgmtApproverL1_status set to 'please_select' --> hide approver attributes for issueimplapproverl2 [I,V]"

	salience 1900
	no-loop true

	when
	    ( user has at object role "issueimplapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "extra_sheet"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_mgmtApproverL1_status" 	invisible
		set "bb_mgmtApproverL1_remark" 	invisible
		set "bb_mgmtApproverL1" 		invisible
		set "bb_mgmtApproverL1_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'extra_sheet' and bb_implApproverL1_status set to 'please_select' --> hide approver attributes for issuemgmtapproverl1[I,V]"

	salience 1900
	no-loop true

	when
		( user has at object role "issueimplapproverl2" OR
		  user has in_general role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "extra_sheet"
		value comparison fulfilled: ":transient:" attr_value "bb_implApproverL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_implApproverL2_aware" 	invisible
		set "bb_implApproverL2" 		invisible
		set "bb_implApproverL2_date" 	invisible
		
end
