package ISSUE_EXTRAPOLATION_RuleSet
expander issue.dsl 

import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelper;
import com.idsscheer.webapps.arcm.bl.component.issuemanagement.re.IssueHelperBB;

#######################################################
### Workflow state "openForCreation" ###

########################
### BB CUSTOMIZATION ###
# rule engine needs to be executed when the attribute value of "bb_issueType" is changed.
rule "bb_issueType set to 'extra_sheet' --> set workflow actors mandatory for creator [I,V]"

	salience 2000
	no-loop true

	when
	    ( is in workflow state "PREPARED" OR
		  is in workflow state "openForCreation" )
	    # during creation the issue manager has the same rights as the creator
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "extra_sheet"

	then
		
		set "bb_mgmtApproverL1_group" 	editable
		set "bb_mgmtApprover_orgunit" 	editable
		
		set "bb_implApproverL2_group" 	editable
		set "bb_implApprover_orgunit" 	editable
		
		set "remark"                  	editable
		set "bb_specificKpiLimit" 		editable
		set "bb_specificKpiLimitAmount" editable
		set "bb_kpiLimitCurrentAmount" 	editable
		set "bb_specificKpiLimitDocs" 	editable
		set "plannedenddate"          	editable
		
		
		
		set "bb_mgmtApproverL1_group" 	mandatory
		set "bb_implApproverL2_group" 	mandatory
		
		set "bb_specificKpiLimit" 		mandatory
		set "bb_specificKpiLimitAmount" mandatory
		set "bb_kpiLimitCurrentAmount" 	mandatory
		set "bb_specificKpiLimitDocs" 	mandatory
		set "plannedenddate"          	mandatory
		
		execute extrapolation rules
		
end


###############################################
### All workflow states - after state rules ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'extra_sheet' --> attributes for creator [I,V]"

	salience 2000
	no-loop true

	when
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "extra_sheet"

	then
		
		set "bb_mgmtApproverL1_group" 	visible
		set "bb_mgmtApproverL1_status" 	visible
		set "bb_mgmtApproverL1_remark" 	visible
		set "bb_mgmtApproverL1" 		visible
		set "bb_mgmtApproverL1_date" 	visible
		set "bb_mgmtApprover_orgunit"	visible
		
		set "bb_implApproverL2_group" 	visible
		set "bb_implApproverL2_aware" 	visible
		set "bb_implApproverL2" 		visible
		set "bb_implApproverL2_date" 	visible
		set "bb_implApprover_orgunit"	visible
		
		#set "owners"            	   	visible
		#set "owner_status"            	visible
		#set "owner"            	   	visible
		#set "reviewers"            	visible
		#set "reviewer_status"          visible
		#set "reviewer_remark"          visible
		#set "reviewer"            		visible
		
		set "remark"                  	visible
		set "bb_specificKpiLimit" 		visible
		set "bb_specificKpiLimitAmount" visible
		set "bb_kpiLimitCurrentAmount" 	visible
		set "bb_specificKpiLimitDocs" 	visible
		set "plannedenddate"          	visible
		#set "immediateMeasure"        	visible
		
		set "remediationMeasure"		not_mandatory
		set "remediationMeasure"		invisible
		
		set "owners" 					invisible
		set "owner" 					invisible
		set "reviewers" 				invisible
		set "reviewer" 					invisible
		
		add object "information" message "info.issuemanagement.execution.phase.not.needed.INF"
		
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'extra_sheet' and bb_mgmtApproverL1_status set to 'please_select' --> hide approver attributes [I,V]"

	salience 1900
	no-loop true

	when
	    # during creation the issue manager has the same rights as the creator
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "extra_sheet"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_mgmtApproverL1_status" 	invisible
		set "bb_mgmtApproverL1_remark" 	invisible
		set "bb_mgmtApproverL1" 		invisible
		set "bb_mgmtApproverL1_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'extra_sheet' and bb_implApproverL2_status set to 'please_select' --> hide approver attributes [I,V]"

	salience 1900
	no-loop true

	when
		( object is opened by its creator OR
		  user has in_general role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "extra_sheet"
		value comparison fulfilled: ":transient:" attr_value "bb_implApproverL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_implApproverL2_aware" 	invisible
		set "bb_implApproverL2" 		invisible
		set "bb_implApproverL2_date" 	invisible
		
end

