package ISSUE_EXECREVIEWERS_TECHRECOMMENDATION_RuleSet
expander issue.dsl

import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelper;
import com.idsscheer.webapps.arcm.bl.component.issuemanagement.re.IssueHelperBB;

#####################################################
### Workflow state "openForReview" ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' and workflow state is 'openForReview' --> attributes for reviewers [I,V]"

	salience 2000
	no-loop true

	when
	    is in workflow state "openForReview"
		user is ":persistent:" member of group in list "bb_reviewers_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation" 

	then
		
		set "reviewer_status" 			editable
		set "reviewer_remark" 			editable
		
		#set "reviewer_remark" 			mandatory
		
end

###############################################
### All workflow states - after state rules ###

#There is a rule in issue_execreviewers_action.drl that defines all visible attributes for 'action' and 'tech_recommendation'

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' --> readonly attributes for reviewers [I,V]"

	salience 2000
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_reviewers_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation"

	then
		
		set "bb_issueOrign" 				visible
		
end


########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' and 'bb_isTechSupportNeeded' equals 'true' --> readonly attributes for reviewers [I,V]"

	salience 2000
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_reviewers_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation" 
		value comparison fulfilled: ":transient:" attr_value "bb_isTechSupportNeeded" "EQUALS" value "true"

	then
		
		set "bb_techApproverL1_group" 		visible
		set "bb_techApproverL1_status" 		visible
		set "bb_techApproverL1_remark" 		visible
		set "bb_techApproverL1" 			visible
		
		set "bb_techApproverL2_group" 		visible
		set "bb_techApproverL2_status" 		visible
		set "bb_techApproverL2_remark" 		visible
		set "bb_techApproverL2" 			visible
		set "bb_techApprover_orgunit" 		visible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' and bb_execImplApprL1_status set to 'please_select' --> hide approver attributes for reviewers [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_reviewers_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation"
		value comparison fulfilled: ":transient:" attr_value "bb_execImplApprL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execImplApprL1_status" 	invisible
		set "bb_execImplApprL1_remark" 	invisible
		set "bb_execImplApprL1" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' and bb_execImplApprL2_status set to 'please_select' --> hide approver attributes for reviewers [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_reviewers_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation"
		value comparison fulfilled: ":transient:" attr_value "bb_execImplApprL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execImplApprL2_status" 	invisible
		set "bb_execImplApprL2_remark" 	invisible
		set "bb_execImplApprL2" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' and reviewer_status contains not 'approved' --> hide reviewer attributes for reviewers [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_reviewers_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation"
		value comparison fulfilled: ":transient:" attr_value "reviewer_status" "CONTAINS" value "undecided"

	then
		
		set "reviewer_status"            	invisible
		set "reviewer_remark"            	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' and bb_execMgmtApprL1_aware is_not filled --> hide approver attributes for reviewers [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_reviewers_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation"
		"bb_execMgmtApprL1_aware" is filled

	then
		
		
		set "bb_execMgmtApprL1_remark" 	visible
		set "bb_execMgmtApprL1" 		visible
		set "bb_execMgmtApprL1_aware" 	visible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' and bb_execMgmtApprL1_status set to 'please_select' --> hide approver attributes for reviewers [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_reviewers_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation"
		value comparison fulfilled: ":transient:" attr_value "bb_execMgmtApprL1_status" "CONTAINS" value "please_select" 


	then
		
		set "bb_execMgmtApprL1_status" 	invisible		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' and reviewer_status contains 'not approved' --> make reviewer_remark attributes mandatory for reviewers [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_reviewers_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation"
		value comparison fulfilled: ":transient:" attr_value "reviewer_status" "CONTAINS" value "not_approved"

	then
		set "reviewer_remark" 				mandatory
		
end


