package ISSUE_EXECOWNERS_TECHRECOMMENDATION_RuleSet
expander issue.dsl

import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelper;
import com.idsscheer.webapps.arcm.bl.component.issuemanagement.re.IssueHelperBB;

########################################################
### Workflow state "openForExecution" ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' and workflow state is 'openForExecution' --> attributes for owners [I,V]"

	salience 2000
	no-loop true

	when
	    is in workflow state "openForExecution"
		user is ":persistent:" member of group in list "bb_owners_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation" 

	then
		
		set "owner"						visible
		
		set "owner_status" 				editable
		set "bb_conclusionPercentage" 	editable
		set "bb_injuredIssue" 			editable
		set "bb_implDocuments" 			editable
		
		set "bb_conclusionPercentage" 	mandatory
		set "bb_injuredIssue" 			mandatory
		set "bb_implDocuments" 			mandatory
		
		validate mandatory documents "tech_recommendation"
		
		
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' and workflow state is 'openForExecution' and bb_injuredIssue is 'true' --> owner_remark is mandatory [I,V]"

	salience 2000
	no-loop true

	when
	    is in workflow state "openForExecution"
		user is ":persistent:" member of group in list "bb_owners_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation" 
		

	then
		
		set "owner_remark" 				visible
		
		set "owner_remark" 				editable
		
		set "owner_remark" 				mandatory
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' and workflow state is 'openForExecution' and owner_status set to 'finished' --> check bb_conclusionPercentage [I,V]"

	salience 2000
	no-loop true

	when
	    is in workflow state "openForExecution"
		user is ":persistent:" member of group in list "bb_owners_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation" 
		value comparison fulfilled: ":transient:" attr_value "owner_status" "CONTAINS" value "finished"
		value comparison fulfilled: ":transient:" attr_value "bb_conclusionPercentage" "CONTAINS NOT" value "hundred"

	then
		
		set "bb_conclusionPercentage" invalid
		add "error" message "error.issue.owner.state.not.allowed.ERR" to "bb_conclusionPercentage"
		
end

###############################################
### All workflow states - after state rules ###

#There is a rule in issue_execowners_action.drl that defines all visible attributes for 'action' and 'tech_recommendation'

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' --> readonly attributes for owners [I,V]"

	salience 2000
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_owners_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation"

	then
		
		set "bb_issueOrign" 				visible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' and 'bb_isTechSupportNeeded' equals 'true' --> readonly attributes for owners [I,V]"

	salience 2000
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_owners_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation" 
		value comparison fulfilled: ":transient:" attr_value "bb_isTechSupportNeeded" "EQUALS" value "true"

	then
		
		set "bb_techApproverL1_group" 		visible
		set "bb_techApproverL1_status" 		visible
		set "bb_techApproverL1_remark" 		visible
		set "bb_techApproverL1" 			visible
		
		set "bb_techApproverL2_group" 		visible
		set "bb_techApproverL2_status" 		visible
		set "bb_techApproverL2_remark" 		visible
		set "bb_techApproverL2" 			visible
		set "bb_techApprover_orgunit" 		visible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' and bb_execImplApprL1_status set to 'please_select' --> hide approver attributes for owners [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_owners_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation"
		value comparison fulfilled: ":transient:" attr_value "bb_execImplApprL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execImplApprL1_status" 	invisible
		set "bb_execImplApprL1_remark" 	invisible
		set "bb_execImplApprL1" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' and bb_execImplApprL2_status set to 'please_select' --> hide approver attributes for owners [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_owners_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation"
		value comparison fulfilled: ":transient:" attr_value "bb_execImplApprL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execImplApprL2_status" 	invisible
		set "bb_execImplApprL2_remark" 	invisible
		set "bb_execImplApprL2" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' and bb_execMgmtApprL1_status set to 'please_select' --> hide approver attributes for owners [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_owners_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation"
		value comparison fulfilled: ":transient:" attr_value "bb_execMgmtApprL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execMgmtApprL1_status" 	invisible
		set "bb_execMgmtApprL1_remark" 	invisible
		set "bb_execMgmtApprL1" 		invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'tech_recommendation' and bb_execMgmtApprL2_status set to 'please_select' --> hide approver attributes for owners [I,V]"

	salience 1900
	no-loop true

	when
		user is ":persistent:" member of group in list "bb_owners_group"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "tech_recommendation"
		value comparison fulfilled: ":transient:" attr_value "bb_execMgmtApprL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_execMgmtApprL2_status" 	invisible
		set "bb_execMgmtApprL2_remark" 	invisible
		set "bb_execMgmtApprL2" 		invisible
		
end