package ISSUE_DEALINGDEADLINE_RuleSet
expander issue.dsl

import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelper;
import com.idsscheer.webapps.arcm.bl.component.issuemanagement.re.IssueHelperBB;

#######################################################
### Workflow state "openForCreation" ###

########################
### BB CUSTOMIZATION ###
# rule engine needs to be executed when the attribute value of "bb_issueType" is changed.
rule "bb_issueType set to 'dealing_deadline' --> set workflow actors mandatory for creator [I,V]"

	salience 2000
	no-loop true

	when
	    ( is in workflow state "PREPARED" OR
		  is in workflow state "openForCreation" )
	    # during creation the issue manager has the same rights as the creator
		( object is opened by its creator OR
		  user has at object role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "dealing_deadline"

	then
		
		set "bb_mgmtApproverL1_group" 		readonly
		set "bb_mgmtApproverL2_group" 		readonly
		set "bb_implApproverL2_group" 		readonly
		
		# begin RD 20161129
		# set "bb_mgmtApprover_orgunit" 		editable
		# set "bb_implApprover_orgunit" 		editable
		set "bb_mgmtApprover_orgunit" 		readonly
		set "bb_implApprover_orgunit" 		readonly
		set "bb_techApprover_orgunit" 		readonly
		# end RD 20161129
		
		set "remark"                  		editable
		set "plannedenddate"          		editable
		set "bb_anotherImportantInfo" 		editable
		set "bb_confidentialityLevel" 		editable
		
		set "bb_mgmtApproverL1_group" 		mandatory
		set "bb_mgmtApproverL2_group" 		mandatory
		set "bb_implApproverL2_group" 		mandatory
		set "remediationMeasure"       		not_mandatory
		set "remediationMeasure"       		invisible
		set "plannedenddate"          		mandatory
		set "bb_confidentialityLevel" 		mandatory
		set "issueRelevantObjects"          mandatory
		
		execute dealing deadline rules

end

###############################################
### All workflow states - after state rules ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'dealing_deadline' --> attributes for creator [I,V]"

	salience 2000
	no-loop true

	when
		( object is opened by its creator OR
		  user has at object role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "dealing_deadline"

	then
		
		set "bb_mgmtApproverL1_group" 		visible
		set "bb_mgmtApproverL1_status" 		visible
		set "bb_mgmtApproverL1_remark" 		visible
		set "bb_mgmtApproverL1" 			visible
		set "bb_mgmtApproverL1_date" 		visible
		
		set "bb_mgmtApproverL2_group" 		visible
		set "bb_mgmtApproverL2_status" 		visible
		set "bb_mgmtApproverL2_remark" 		visible
		set "bb_mgmtApproverL2" 			visible
		set "bb_mgmtApproverL2_date" 		visible
		set "bb_mgmtApprover_orgunit"		visible
		
		set "bb_implApproverL2_group" 		visible
		set "bb_implApproverL2_status" 		visible
		set "bb_implApproverL2_remark" 		visible
		set "bb_implApproverL2" 			visible
		set "bb_implApproverL2_date" 		visible
		set "bb_implApprover_orgunit"		visible
		
		set "remark"                  		visible
		set "plannedenddate"          		visible
		set "bb_anotherImportantInfo" 		visible
		set "bb_confidentialityLevel" 		visible
		set "bb_isTechSupportNeeded" 		visible
		
		set "owners" 						invisible
		set "owner" 						invisible
		set "reviewers" 					invisible
		set "reviewer" 						invisible
		add object "information" message "info.issuemanagement.execution.phase.not.needed.INF"
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'dealing_deadline' and 'bb_isTechSupportNeeded' equals 'true' --> readonly attributes for creator [I,V]"

	salience 2000
	no-loop true

	when
		( object is opened by its creator OR
		  user has at object role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "dealing_deadline"
		value comparison fulfilled: ":transient:" attr_value "bb_isTechSupportNeeded" "EQUALS" value "true"

	then
		
		set "bb_techApproverL1_group" 		visible
		set "bb_techApproverL1_status" 		visible
		set "bb_techApproverL1_remark" 		visible
		set "bb_techApproverL1" 			visible
		set "bb_techApproverL1_date" 		visible
		
		set "bb_techApprover_orgunit" 		visible
		
end

rule "ISSUE has been accepted by the mgmtApproverL1 --> 'bb_dealingDeadlineDate' must not be less than today [I,V]"

	salience 2100
	no-loop true

	when
		"bb_dealingDeadlineDate" is dirty
		"bb_dealingDeadlineDate" is filled
		value comparison fulfilled: ":transient:" attr_value "bb_dealingDeadlineDate" "LESS THAN" value ":TODAY:"

	then
		set "bb_dealingDeadlineDate" invalid
		add "error" message "issue.remediation.planned.before.not.before.today.ERR" to "bb_dealingDeadlineDate"

end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'dealing_deadline' and bb_implApproverL2_status set to 'please_select' --> hide approver attributes for creator [I,V]"

	salience 1900
	no-loop true

	when
		( object is opened by its creator OR
		  user has at object role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "dealing_deadline"
		value comparison fulfilled: ":transient:" attr_value "bb_implApproverL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_implApproverL2_status" 	invisible
		set "bb_implApproverL2_remark" 	invisible
		set "bb_implApproverL2" 		invisible
		set "bb_implApproverL2_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'dealing_deadline' and bb_techApproverL1_status set to 'please_select' --> hide approver attributes for creator [I,V]"

	salience 1900
	no-loop true

	when
		( object is opened by its creator OR
		  user has at object role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "dealing_deadline"
		value comparison fulfilled: ":transient:" attr_value "bb_techApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_techApproverL1_status" 	invisible
		set "bb_techApproverL1_remark" 	invisible
		set "bb_techApproverL1" 		invisible
		set "bb_techApproverL1_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'dealing_deadline' and bb_mgmtApproverL1_status set to 'please_select' --> hide approver attributes for creator [I,V]"

	salience 1900
	no-loop true

	when
		( object is opened by its creator OR
		  user has at object role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "dealing_deadline"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_mgmtApproverL1_status" 	invisible
		set "bb_mgmtApproverL1_remark" 	invisible
		set "bb_mgmtApproverL1" 		invisible
		set "bb_mgmtApproverL1_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'dealing_deadline' and bb_mgmtApproverL2_status set to 'please_select' --> hide approver attributes for creator [I,V]"

	salience 1900
	no-loop true

	when
		( object is opened by its creator OR
		  user has at object role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "dealing_deadline"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_mgmtApproverL2_status" 	invisible
		set "bb_mgmtApproverL2_remark" 	invisible
		set "bb_mgmtApproverL2" 		invisible
		set "bb_mgmtApproverL2_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "IF 'bb_dealingDeadlineDate' is filled --> 'bb_dealingDeadlineDate' is visible for issuemanager [I,V]"

	salience 2000
	no-loop true

	when
		( object is opened by its creator OR
		  user has at object role "issuemanager" OR
		  user is ":persistent:" member of group in list "bb_creators_group" )
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "dealing_deadline"
	    "bb_dealingDeadlineDate" is filled  
		
	then
		
		set "bb_dealingDeadlineDate" visible		
end
