package ISSUE_DEALINGDEADLINE_IRO_RuleSet
expander issue.dsl

import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelper;
import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelperBB;
import com.idsscheer.webapps.arcm.bl.component.issuemanagement.re.IssueHelperBB;

rule "IRO visible attributes - 'dealing_deadline' [I,V]"

	salience 10
	no-loop true
	
	when
		is IRO
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "dealing_deadline"
				
	then
		set object readonly
		remove object messages	

		set "bb_mgmtApproverL1_group" 		visible
		set "bb_mgmtApproverL1_status" 		visible
		set "bb_mgmtApproverL1_remark" 		visible
		set "bb_mgmtApproverL1" 			visible
		set "bb_mgmtApproverL1_date" 		visible
		
		set "bb_mgmtApproverL2_group" 		visible
		set "bb_mgmtApproverL2_status" 		visible
		set "bb_mgmtApproverL2_remark" 		visible
		set "bb_mgmtApproverL2" 			visible
		set "bb_mgmtApproverL2_date" 		visible
		set "bb_mgmtApprover_orgunit"		visible
		
		set "bb_implApproverL2_group" 		visible
		set "bb_implApproverL2_status" 		visible
		set "bb_implApproverL2_remark" 		visible
		set "bb_implApproverL2" 			visible
		set "bb_implApproverL2_date" 		visible
		set "bb_implApprover_orgunit"		visible
		
		set "remark"                  		visible
		set "plannedenddate"          		visible
		set "bb_anotherImportantInfo" 		visible
		set "bb_confidentialityLevel" 		visible
		set "bb_isTechSupportNeeded" 		visible

end

rule "IRO visible attributes - 'dealing_deadline'- tech support [I,V]"

	salience 9
	no-loop true
	
	when
		is IRO
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "dealing_deadline"
		value comparison fulfilled: ":transient:" attr_value "bb_isTechSupportNeeded" "EQUALS" value "true"

	then
		set "bb_techApproverL1_group" 		visible
		set "bb_techApproverL1_status" 		visible
		set "bb_techApproverL1_remark" 		visible
		set "bb_techApproverL1" 			visible
		set "bb_techApproverL1_date" 		visible
		
		set "bb_techApprover_orgunit" 		visible

end
