package ISSUE_IMPLAPPL2_DEALINGDEADLINE_RuleSet
expander issue.dsl

import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelper;
import com.idsscheer.webapps.arcm.bl.component.issuemanagement.re.IssueHelperBB;

#################################################################
### Workflow state "openForCreationDealingDeadlineImplApprL2" ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'dealing_deadline' and workflow state is 'openForCreationDealingDeadlineImplApprL2' --> attributes for issueimplapproverl2 [I,V]"

	salience 2000
	no-loop true

	when
	    is in workflow state "openForCreationDealingDeadlineImplApprL2"
		user has at object role "issueimplapproverl2"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "dealing_deadline"

	then
		
		set "bb_implApproverL2_status" 		editable
		set "bb_implApproverL2_remark" 		editable
		
end

########################
### BB CUSTOMIZATION ###
rule "ISSUE has been rejected by the implApproverL2 workflow state is 'openForCreationDealingDeadlineImplApprL2' --> 'bb_implApproverL2_remark' is mandatory [I,V]"

	salience 2000
	no-loop true

	when
		is in workflow state "openForCreationDealingDeadlineImplApprL2" 
		user has at object role "issueimplapproverl2" 
		value comparison fulfilled: ":transient:" attr_value "bb_implApproverL2_status" "CONTAINS" value "rejected"

	then
		
		set "bb_implApproverL2_remark" 	mandatory
end

###############################################
### All workflow states - after state rules ###

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'dealing_deadline' --> readonly attributes for issueimplapproverl2 [I,V]"

	salience 2000
	no-loop true

	when
		user has at object role "issueimplapproverl2"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "dealing_deadline"

	then
		
		set "bb_mgmtApproverL1_group" 		visible
		set "bb_mgmtApproverL1_status" 		visible
		set "bb_mgmtApproverL1_remark" 		visible
		set "bb_mgmtApproverL1" 			visible
		set "bb_mgmtApproverL1_date" 		visible
		
		set "bb_mgmtApproverL2_group" 		visible
		set "bb_mgmtApproverL2_status" 		visible
		set "bb_mgmtApproverL2_remark" 		visible
		set "bb_mgmtApproverL2" 			visible
		set "bb_mgmtApproverL2_date" 		visible
		set "bb_mgmtApprover_orgunit"		visible
		
		set "bb_implApproverL2_group" 		visible
		set "bb_implApproverL2_status" 		visible
		set "bb_implApproverL2_remark" 		visible
		set "bb_implApproverL2" 			visible
		set "bb_implApproverL2_date" 		visible
		set "bb_implApprover_orgunit"		visible
		
		set "remark"                  		visible
		set "plannedenddate"          		visible
		set "bb_anotherImportantInfo" 		visible
		set "bb_confidentialityLevel" 		visible
		set "bb_isTechSupportNeeded" 		visible
		
		set "owners" 						invisible
		set "owner" 						invisible
		set "reviewers" 					invisible
		set "reviewer" 						invisible
		add object "information" message "info.issuemanagement.execution.phase.not.needed.INF"
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'dealing_deadline' and 'bb_isTechSupportNeeded' equals 'true' --> readonly attributes for issueimplapproverl2 [I,V]"

	salience 2000
	no-loop true

	when
		user has at object role "issueimplapproverl2"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "dealing_deadline"
		value comparison fulfilled: ":transient:" attr_value "bb_isTechSupportNeeded" "EQUALS" value "true"

	then
		
		set "bb_techApproverL1_group" 		visible
		set "bb_techApproverL1_status" 		visible
		set "bb_techApproverL1_remark" 		visible
		set "bb_techApproverL1" 			visible
		set "bb_techApproverL1_date" 		visible
		
		set "bb_techApprover_orgunit" 		visible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'dealing_deadline' and bb_implApproverL2_status set to 'please_select' --> hide approver attributes for issueimplapproverl2 [I,V]"

	salience 1900
	no-loop true

	when
		user has at object role "issueimplapproverl2"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "dealing_deadline"
		value comparison fulfilled: ":transient:" attr_value "bb_implApproverL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_implApproverL2_status" 	invisible
		set "bb_implApproverL2_remark" 	invisible
		set "bb_implApproverL2" 		invisible
		set "bb_implApproverL2_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'dealing_deadline' and bb_techApproverL1_status set to 'please_select' --> hide approver attributes for issueimplapproverl2 [I,V]"

	salience 1900
	no-loop true

	when
		user has at object role "issueimplapproverl2"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "dealing_deadline"
		value comparison fulfilled: ":transient:" attr_value "bb_techApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_techApproverL1_status" 	invisible
		set "bb_techApproverL1_remark" 	invisible
		set "bb_techApproverL1" 		invisible
		set "bb_techApproverL1_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'dealing_deadline' and bb_mgmtApproverL1_status set to 'please_select' --> hide approver attributes for issueimplapproverl2 [I,V]"

	salience 1900
	no-loop true

	when
		user has at object role "issueimplapproverl2"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "dealing_deadline"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL1_status" "CONTAINS" value "please_select"

	then
		
		set "bb_mgmtApproverL1_status" 	invisible
		set "bb_mgmtApproverL1_remark" 	invisible
		set "bb_mgmtApproverL1" 		invisible
		set "bb_mgmtApproverL1_date" 	invisible
		
end

########################
### BB CUSTOMIZATION ###
rule "bb_issueType set to 'dealing_deadline' and bb_mgmtApproverL2_status set to 'please_select' --> hide approver attributes for issueimplapproverl2 [I,V]"

	salience 1900
	no-loop true

	when
		user has at object role "issueimplapproverl2"
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "dealing_deadline"
		value comparison fulfilled: ":transient:" attr_value "bb_mgmtApproverL2_status" "CONTAINS" value "please_select"

	then
		
		set "bb_mgmtApproverL2_status" 	invisible
		set "bb_mgmtApproverL2_remark" 	invisible
		set "bb_mgmtApproverL2" 		invisible
		set "bb_mgmtApproverL2_date" 	invisible
		
end
########################
### BB CUSTOMIZATION ###
rule "IF 'bb_dealingDeadlineDate' is filled --> 'bb_dealingDeadlineDate' is visible for issueimplapproverl2 [I,V]"

	salience 2000
	no-loop true

	when
		user has at object role "issueimplapproverl2"		  
		value comparison fulfilled: ":transient:" attr_value "bb_issueType" "CONTAINS" value "dealing_deadline"
	    "bb_dealingDeadlineDate" is filled  
		
	then
		
		set "bb_dealingDeadlineDate" visible		
end
